### PR TITLE
Adds wall drawings #16 and #85

### PR DESCRIPTION
**Pull request by y-a-v-a**
This time no canvas but plain old CSS!

### CODE REVIEW

**Comment by doolittle** [comment]
@y-a-v-a can you add these to `solutions.json`?

**Comment by y-a-v-a** [comment]
Will update!

**Comment by y-a-v-a** [comment]
Done updating `solutions.json` and changed code of 085 a bit.

**Comment by doolittle** [comment]
screen shot 2016-11-09 at 11 03 55 am


Thanks, @y-a-v-a! Nice solution to #16--very elegant.

**Pull request merged**
