### PR TITLE
#122

### PR DESCRIPTION
**Pull request by y-a-v-a**
Hi,
Spent some time on a new wall drawing. For reference, I've used, apart from the description within the instructions.md, this link:
http://www.huffingtonpost.com/alexander-adler/sol-lewitt-arcs-and-lines_b_870641.html

Cheers!
Vincent

### CODE REVIEW

**Comment by y-a-v-a** [comment]
I just noticed some unexpected behaviour in Safari... will look into that asap.

**Comment by y-a-v-a** [comment]
fixed the safari 'bug'.

**Comment by doolittle** [comment]
Looks great, thanks @y-a-v-a!

**Comment by y-a-v-a** [comment]
Thanks! It's been a while, but I still enjoy to create one, now and then. ;-)

**Pull request merged**
